### ISSUE TITLE
CLI no longer works

### ISSUE THREAD

**Issue by olydis** [Azure/oav#118] opened 2017-05-17 16:12 UTC
Tried on Windows and Ubuntu (on Windows):

```
npm i -g oav                         # successfully installs oav@0.4.1
oav validate-examples <swagger>      # outputs absolutely nothing, while the same swagger is flagged by CI
```

Adding any logging level does not change this.
On the other hand, `oav validate-spec` seems to work.

**Comment by vishrutshah** [comment] 2017-05-22 20:59
The issue is in the [ms-rest](https://www.npmjs.com/package/ms-rest) runtime. The issue is on line let [segments = url.match(/({\w*\s*\w*})/ig);](https://github.com/Azure/azure-sdk-for-node/blob/9b6b146ad0c9dfa49f4c71eb9782d548ffee21c5/runtime/ms-rest/lib/webResource.js#L168) which does not handle the `-` present in the url `"https://management.azure.com/storage/{storage-account-name}"`

I'll open a bug in the nodeJs repo for that to be fixed in runtime.

**Comment by veronicagg** [comment] 2017-07-13 01:17
@vishrutshah could this issue be closed? I assume this is now working?

**Comment by vishrutshah** [comment] 2017-07-13 16:08
I haven't got chance to investigate it for `oav validate-examples`. I'd like to look into this just for verification before we close it. Let's keep it on my radar until I verify.

**Comment by vishrutshah** [comment] 2017-07-14 15:32
Verified. Commandline is working with version `0.4.7`

Example:
```
vishrut@visshamac oav (master) $ oav --version
0.4.7
vishrut@mac oav (master) $ oav validate-example /Users/vishrut/git-repos/azure-rest-api-specs/specification/storage/resource-manager/Microsoft.Storage/2017-06-01/storage.json
error: Found errors in validating the request for x-ms-example "StorageAccountCheckNameAvailability" in operation "StorageAccounts_CheckNameAvailability".:
 
{ code: 'REQUEST_VALIDATION_ERROR',
  message: 'Found errors in validating the request for x-ms-example "StorageAccountCheckNameAvailability" in operation "StorageAccounts_CheckNameAvailability".',
  innerErrors: 
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors: 
        [ { code: 'ENUM_MISMATCH',
            params: [ 'Microsoft.Storage/storageAccount' ],
            message: 'No enum match for: Microsoft.Storage/storageAccount',
            path: [ 'type' ],
            description: 'The type of resource, Microsoft.Storage/storageAccounts' } ],
       in: 'body',
       message: 'Invalid parameter (accountName): Value failed JSON Schema validation',
       name: 'accountName',
       path: 
        [ 'paths',
          '/subscriptions/{subscriptionId}/providers/Microsoft.Storage/checkNameAvailability',
          'post',
          'parameters',
          '0' ] } ] }

```

**Closed by vishrutshah** 2017-07-14 15:32 UTC
Labels: bug, investigate
