### ISSUE TITLE
OAV should not escape the ':' symbol.

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/oav#174] opened 2017-10-19 18:49 UTC
Currently, OAV escapes the ':' symbol. For example, if an operation has this parameter

```json
{
  "name": "srs", 
  "in": "query", 
  "description": "Projection used in describing the bbox", 
  "required": true, 
  "default": "EPSG:4326", 
  "enum": [ 
    "EPSG:4326", 
    "EPSG:3857" 
  ], 
  "type": "string" 
} 
```

And an example set this parameter like this

```json
 "srs": "EPSG:4326", 
```

Then OAV shows this error:

```
{ code: 'REQUEST_VALIDATION_ERROR',
  id: 'OAV109',
  message: 'Found errors in validating the request for x-ms-example "GetMapStaticTile" in operation "GetMapStaticTile".',
  innerErrors: 
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors: 
        [ { code: 'ENUM_MISMATCH',
            params: [ 'EPSG%3A4326' ],
            message: 'No enum match for: EPSG%3A4326',
            path: [],
            description: 'Projection used in describing the bbox' } ],
       in: 'query',
       message: 'Invalid parameter (srs): Value failed JSON Schema validation',
       name: 'srs',
       path: [ 'paths', '/map/static/{format}', 'get', 'parameters', '5' ] } ] }
```

According to Stackoverflow :-) https://stackoverflow.com/questions/2322764/what-characters-must-be-escaped-in-an-http-query-string the symbol may not be escaped.

See this PR https://github.com/Azure/azure-rest-api-specs-pr/pull/221/files and Travis-CI https://travis-ci.com/Azure/azure-rest-api-specs-pr/jobs/95111718

Releated issue https://github.com/Azure/oav/issues/80

## Proposed Solutions

The server should unescape the received value and then compare it. So, OAV tool should do the same. Because there are different escaped representation of the same value.

**Comment by mcardosos** [comment] 2018-01-09 02:32
Some progress on finding the problem.
Bug happens [here](https://github.com/Azure/oav/blob/master/lib/validators/specValidator.js#L696). Apparently it is a problem that comes from ms-rest module.

**Comment by mcardosos** [comment] 2018-01-09 19:35
After talking with @amarzavery , The issue is in the swagger, not in the tool. The parameter should include [x-ms-skip-url-encoding](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-skip-url-encoding)

**Comment by veronicagg** [comment] 2018-01-09 22:58
@mcardosos thanks for investigating, if that's the case,  could you open an issue on the azure-rest-api-specs repo for the spec having this problem and tag the author of the PR which contained the issue? This way it could get fixed.
Feel free to close this issue, if there are no other action items on it. Thanks!

**Comment by mcardosos** [comment] 2018-01-09 23:51
Cool PR https://github.com/amarzavery/sway/pull/15

**Closed** 2018-01-17 18:29 UTC
Labels: Sprint-112
