### ISSUE TITLE
[model-validator] does not handle pathParameters when it contains - in the pathTemplate

### ISSUE THREAD

**Issue by olydis** [Azure/oav#119] opened 2017-05-17 16:19 UTC
See https://travis-ci.org/Azure/azure-rest-api-specs/jobs/233056487#L1170

``` JS
{ code: 'REQUEST_VALIDATION_ERROR',
  message: 'Found errors in validating the request for x-ms-example "Delete Storage account" in operation "DeleteStorageAccount".',
  innerErrors: 
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors: 
        [ { code: 'REQUIRED',
            message: 'Value is required but was not provided',
            path: 
             [ 'paths',
               '/storage/{storage-account-name}',
               'delete',
               'parameters',
               '0' ] } ],
       in: 'path',
       message: 'Invalid parameter (storage-account-name): Value is required but was not provided',
       name: 'storage-account-name',
       path: { '$ref': '$["innerErrors"][0]["errors"][0]["path"]' } } ] }
```

(side note: what is `path: { '$ref': '$["innerErrors"][0]["errors"][0]["path"]' } } ] }` supposed to mean? I remember trying to derive blame paths from values provided here in AutoRest core)

However, the example does provide this parameter and there is no spelling mismatch or similar:

``` JSON
{
   "parameters":{
      "storage-account-name":"deleteStrg01",
      "api-version":"2016-10-01"
   },
   "responses":{
      "200":{
         "headers":{

         },
         "body":{
            "id":"https://storage-sdk-test.vault-int.azure-int.net/storage/deleteStrg01",
            "resourceId":"/subscriptions/{subId}/resourceGroups/{rgName}/providers/Microsoft.Storage/storageAccounts/kvstorageacc",
            "activeKeyName":"key1",
            "autoRegenerateKey":true,
            "regenerationPeriod":"P30D",
            "attributes":{
               "enabled":true,
               "created":1490738386,
               "updated":1490738386
            },
            "tags":{"tag1":"val1", "tag2":"val2"}
         }
      }
   }
}
```

**Comment by vishrutshah** [comment] 2017-05-22 21:03
The issue is in the [ms-rest](https://www.npmjs.com/package/ms-rest) runtime. The issue is on line let [segments = url.match(/({\w*\s*\w*})/ig);](https://github.com/Azure/azure-sdk-for-node/blob/9b6b146ad0c9dfa49f4c71eb9782d548ffee21c5/runtime/ms-rest/lib/webResource.js#L168) which does not handle the `-` present in the url `"https://management.azure.com/storage/{storage-account-name}"`

I'll open a bug in the nodeJs repo for that to be fixed in runtime.

**Comment by amarzavery** [comment] 2017-07-13 16:17
I would recommend people to not put dashes in the names of path parameters. They are mere place holders. When they put dashes, Autorest will also remove the dashes and convert the parameter name into PascalCase or camelCase for a given language. `Sway` does not like dashes in path parameters as well.

for example
Instead of providing path parameters like this `/subscriptions/{subscription-id}/resourceGroups/{resource-group-name}`  one can provide it like this: `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}`.
This is only for path parameters. Having dashes in query parameters and header parameters is fine. They are not placeholders. However path parameters are pure placeholders. Having a linter rule for the same would be great.

@veronicagg  @vishrutshah what do you guys think?

**Comment by vishrutshah** [comment] 2017-07-13 16:20
It seems reasonable to me. Is there a way that we can detect early when people are adding dash in path parameter, so that we can flag early instead of our `model-validator` failing?

**Comment by amarzavery** [comment] 2017-07-13 16:43
Linter rule is the best way. In ideal scenario people would use the vscode extension while authoring swaggers and this will stop them by throwing a linter error. Thus before sending the PR this issue should not exist.

**Comment by veronicagg** [comment] 2017-07-13 17:04
@amarzavery ok, I'll open another issue on the linter repo (not sure when we'll get to implement this rule), and will link to this issue, so we can close this one, as it appears that there's no action item to take on this one.  thanks!

**Closed** 2017-07-13 17:06 UTC
Labels: bug, customer-request
