### ISSUE TITLE
OAV 2.5.5: no such file or directory markdownReport.handlebars

### ISSUE THREAD

**Issue by molson194** [Azure/oav#626] opened 2021-06-21 19:41 UTC
The validate-spec command in version 2.5.4 of OAV was successfully ran, but when upgrading to 2.5.5, I started getting the error below.

Command Run:
`oav validate-spec "<PATH TO SWAGGER FILE>"
`

Error:
```
Error: ENOENT: no such file or directory, open 'C:\npm\prefix\node_modules\oav\dist\lib\testScenario\templates\markdownReport.handlebars'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.exports.compileHandlebarsTemplate (C:\npm\prefix\node_modules\oav\dist\lib\testScenario\markdownReport.js:57:41)
    at Object.<anonymous> (C:\npm\prefix\node_modules\oav\dist\lib\testScenario\markdownReport.js:62:30)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\npm\\prefix\\node_modules\\oav\\dist\\lib\\testScenario\\templates\\markdownReport.handlebars'
}
```

Thanks in advance for the help!

**Comment by zhenglaizhang** [comment] 2021-06-22 09:43
thanks @molson194 we are active working the fix, should release in next a few days.

**Comment by zhenglaizhang** [comment] 2021-07-01 06:48
As new package oav@2.5.8 has been released, and the issue is fixed, closing the issue

**Closed by zhenglaizhang** 2021-07-01 06:48 UTC

**Comment by molson194** [comment] 2022-04-20 22:32
Sorry to re-open, but we started hitting this issue again yesterday @zhenglaizhang 

```
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\npm\prefix\node_modules\oav\dist\lib\apiScenario\templates\markdownReport.handlebars'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.exports.compileHandlebarsTemplate (C:\npm\prefix\node_modules\oav\dist\lib\apiScenario\markdownReport.js:94:41)
    at Object.<anonymous> (C:\npm\prefix\node_modules\oav\dist\lib\apiScenario\markdownReport.js:99:44)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\npm\\prefix\\node_modules\\oav\\dist\\lib\\apiScenario\\templates\\markdownReport.handlebars'
}
```

**Comment by molson194** [comment] 2022-04-20 22:47
Opened a new issue here: https://github.com/Azure/oav/issues/783
