### ISSUE TITLE
[ONE_OF_MISSING] Think about improving errors 

### ISSUE THREAD

**Issue by vishrutshah** [Azure/oav#173] opened 2017-10-19 00:00 UTC
```
vishrut@visshamac oav (polymorphic-validation) $ node cli.js validate-example /Users/vishrut/git-repos/oav/test/modelValidation/swaggers/specification/polymorphic/polymorphicSwagger.json -o CircularAnimal_IncorrectSibling_List
error: Found errors in validating the response with statusCode "200" for x-ms-example "Tests ploymorphic circular array, dictionary of animals with incorrect sibling (negative)" in operation "CircularAnimal_IncorrectSibling_List".:
 
{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Tests ploymorphic circular array, dictionary of animals with incorrect sibling (negative)" in operation "CircularAnimal_IncorrectSibling_List".',
  innerErrors: 
   [ { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: 'ONE_OF_MISSING',
            params: [],
            message: 'Data does not match any schemas from \'oneOf\'',
            path: [ 'value', '3' ],
            inner: 
             [ { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                 params: [ [ 'eats' ] ],
                 message: 'Additional properties not allowed: eats',
                 path: [ 'value', '3' ],
                 description: 'An animal.' },
               { code: 'ONE_OF_MISSING',
                 params: [],
                 message: 'Data does not match any schemas from \'oneOf\'',
                 path: [ 'value', '3', 'siblings', '0' ],
                 inner: 
                  [ { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'eats', 'sanctuary' ] ],
                      message: 'Additional properties not allowed: eats,sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'An animal.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'Base class for all Mammals.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'class for Mouse mammal animal.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'class for Cat.' },
                    { code: 'ENUM_MISMATCH',
                      params: [ 'Microsoft.Mammal' ],
                      message: 'No enum match for: Microsoft.Mammal',
                      path: [ 'siblings', '0', 'animalType' ],
                      description: 'Type of activity.' } ] },
               { code: 'ONE_OF_MISSING',
                 params: [],
                 message: 'Data does not match any schemas from \'oneOf\'',
                 path: [ 'value', '3', 'siblings', '0' ],
                 inner: 
                  [ { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'eats', 'sanctuary' ] ],
                      message: 'Additional properties not allowed: eats,sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'An animal.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'Base class for all Mammals.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'class for Mouse mammal animal.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'class for Cat.' },
                    { code: 'ENUM_MISMATCH',
                      params: [ 'Microsoft.Mammal' ],
                      message: 'No enum match for: Microsoft.Mammal',
                      path: [ 'siblings', '0', 'animalType' ],
                      description: 'Type of activity.' } ] },
               { code: 'ONE_OF_MISSING',
                 params: [],
                 message: 'Data does not match any schemas from \'oneOf\'',
                 path: [ 'value', '3', 'siblings', '0' ],
                 inner: 
                  [ { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'eats', 'sanctuary' ] ],
                      message: 'Additional properties not allowed: eats,sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'An animal.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'Base class for all Mammals.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'class for Mouse mammal animal.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'class for Cat.' },
                    { code: 'ENUM_MISMATCH',
                      params: [ 'Microsoft.Mammal' ],
                      message: 'No enum match for: Microsoft.Mammal',
                      path: [ 'siblings', '0', 'animalType' ],
                      description: 'Type of activity.' } ] },
               { code: 'ONE_OF_MISSING',
                 params: [],
                 message: 'Data does not match any schemas from \'oneOf\'',
                 path: [ 'value', '3', 'siblings', '0' ],
                 inner: 
                  [ { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'eats', 'sanctuary' ] ],
                      message: 'Additional properties not allowed: eats,sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'An animal.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'Base class for all Mammals.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'class for Mouse mammal animal.' },
                    { code: 'OBJECT_ADDITIONAL_PROPERTIES',
                      params: [ [ 'sanctuary' ] ],
                      message: 'Additional properties not allowed: sanctuary',
                      path: [ 'siblings', '0' ],
                      description: 'class for Cat.' },
                    { code: 'ENUM_MISMATCH',
                      params: [ 'Microsoft.Mammal' ],
                      message: 'No enum match for: Microsoft.Mammal',
                      path: [ 'siblings', '0', 'animalType' ],
                      description: 'Type of activity.' } ] } ] } ],
       message: 'Invalid body: Data does not match any schemas from \'oneOf\'',
       path: [] } ] }
```

**Comment by vladbarosan** [comment] 2018-05-22 06:19
Duplicate of https://github.com/Azure/oav/issues/173

**Closed by vladbarosan** 2018-05-22 06:19 UTC
Labels: P2
